'use client';
import {useEffect,useRef,useState} from 'react';
import type {DemoProfile} from '@saas/contracts';
import {previewRecovery,restoreRecovery,type RecoveryPreview} from './offline';
export default function RecoveryDialog({scope,close,saved}:{scope:DemoProfile;close:()=>void;saved:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const [text,setText]=useState('');const [preview,setPreview]=useState<RecoveryPreview|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{dialog.current?.showModal();},[]);
 async function select(file?:File){setError('');setPreview(null);setText('');if(!file)return;setBusy(true);try{if(file.size>10*1024*1024)throw new Error('الحد الأقصى للملف ١٠ ميجابايت.');const content=await file.text();const result=await previewRecovery(content,scope);setText(content);setPreview(result);}catch(e){setError(e instanceof Error?e.message:'تعذر قراءة الملف');}finally{setBusy(false);}}
 async function restore(){setBusy(true);setError('');try{await restoreRecovery(text,scope);saved();}catch(e){setError(e instanceof Error?e.message:'تعذر الاسترداد');}finally{setBusy(false);}}
 return <dialog ref={dialog} className="modal" aria-labelledby="recovery-title" onCancel={e=>{e.preventDefault();if(!busy)close();}}><div className="panel-heading"><div><h2 id="recovery-title">استعادة العمليات</h2><p>راجع الملف قبل إضافته إلى المؤسسة الحالية.</p></div><button className="icon-button" aria-label="إغلاق الاسترداد" disabled={busy} onClick={close}>×</button></div><div className="recovery-body"><label>ملف الاسترداد<input aria-label="ملف الاسترداد" type="file" accept=".json,application/json" disabled={busy} onChange={e=>void select(e.target.files?.[0])}/></label>{preview&&<div className="recovery-preview"><p>عمليات جديدة: <strong>{preview.newCount}</strong></p><p>موجودة على هذا الجهاز: <strong>{preview.duplicateCount}</strong></p><p>مقبولة سابقاً على الخادم: <strong>{preview.acceptedCount}</strong></p>{preview.legacyCount>0&&<p>بعض السجلات من نسخة قديمة بدون هوية جهاز المصدر.</p>}<p>لن تتكرر العمليات الموجودة. تُراجع العمليات المستوردة عند المزامنة قبل تغيير الرصيد المؤكد.</p></div>}{error&&<p role="alert" className="error">{error}</p>}<div className="modal-actions"><button className="primary" disabled={!preview||busy} onClick={()=>void restore()}>{busy?'جارٍ المعالجة…':'تأكيد الاسترداد'}</button><button className="secondary" disabled={busy} onClick={close}>إلغاء</button></div></div></dialog>;
}
