'use client';
import {useCallback,useEffect,useState,useRef} from 'react';
import {useLiveQuery} from 'dexie-react-hooks';
import {useForm} from 'react-hook-form';
import {commandSchema,type Command,type DemoProfile,type Snapshot} from '@saas/contracts';
import {decimal,projectedQuantity} from '@saas/domain';
import {local,bootstrap,sync,saveCommand,downloadRecovery,resolveReview,type LocalCommand} from './offline';
import {useUI,type View} from './store';
import RecoveryDialog from './RecoveryDialog';
import BuildVersion from './BuildVersion';

const labels:Record<View,string>={overview:'نظرة عامة',inventory:'المخزون',activity:'سجل الحركات',sync:'مركز المزامنة'};
const number=(v:string|number,digits=2)=>new Intl.NumberFormat('ar-EG',{maximumFractionDigits:digits}).format(Number(v));
const normalizeDecimal=(v:string)=>v.replace(/[٠-٩]/g,c=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(c))).replace(/[۰-۹]/g,c=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(c))).replace(/٫/g,'.').trim();
const date=(v:string)=>new Intl.DateTimeFormat('ar-EG',{dateStyle:'medium',timeStyle:'short',timeZone:'Africa/Cairo'}).format(new Date(v));
function Icon({name}:{name:string}) {const paths:Record<string,string>={overview:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',inventory:'m3 7 9-4 9 4v10l-9 4-9-4z M3 7l9 4 9-4 M12 11v10',activity:'M5 3v18h14V3z M8 8h8 M8 12h8 M8 16h5',sync:'M20 7a9 9 0 0 0-15-2L3 7 M3 3v4h4 M4 17a9 9 0 0 0 15 2l2-2 M21 21v-4h-4',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14 M15 15l6 6',plus:'M12 5v14 M5 12h14',arrow:'M5 12h14 M12 5l7 7-7 7',check:'m4 12 5 5L20 6',close:'m6 6 12 12 M18 6 6 18',leaf:'M20 3C8 2 2 9 7 16s15 0 13-13 M6 20 17 7'};return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.inventory}/></svg>;}

export default function Workspace(){
 const [editing,setEditing]=useState<LocalCommand|undefined>();const [recoveryOpen,setRecoveryOpen]=useState(false);
 const [scope,setScope]=useState<DemoProfile|null>(null);const [ready,setReady]=useState(false);const [online,setOnline]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [offlineReady,setOfflineReady]=useState(false);const [modal,setModal]=useState<Command['type']|null>(null);const [selected,setSelected]=useState<string|null>(null);const [category,setCategory]=useState('all');const [stockFilter,setStockFilter]=useState('all');const operationTrigger=useRef<HTMLButtonElement|null>(null);useEffect(()=>{if(!modal)operationTrigger.current?.focus();},[modal]);
 const {view,location,search,setView,setLocation,setSearch}=useUI();
 const snapshot=useLiveQuery(()=>scope?local.snapshots.get(scope):undefined,[scope]);
 const commands=useLiveQuery(()=>scope?local.commands.where('scope').equals(scope).toArray():[],[scope],[]);
 const pending=commands.filter(c=>c.status==='pending'||c.status==='acceptedAwaiting');const review=commands.filter(c=>c.status==='needsReview');
 useEffect(()=>{let alive=true;const connection=()=>{setOnline(navigator.onLine);};connection();window.addEventListener('online',connection);window.addEventListener('offline',connection);
  (async()=>{try{const pref=await local.preferences.get('scope');if(alive&&pref)setScope(pref.value as DemoProfile);if('serviceWorker'in navigator){const registration=await navigator.serviceWorker.register('/sw.js');const controller=()=>setOfflineReady(!!navigator.serviceWorker.controller);navigator.serviceWorker.addEventListener('controllerchange',controller);controller();if(registration.active)controller();}}catch{ /* Development builds have no precache; stored business data is still durable. */ }finally{if(alive)setReady(true);}})();
  return()=>{alive=false;window.removeEventListener('online',connection);window.removeEventListener('offline',connection);};
 },[]);
 const synchronize=useCallback(async()=>{if(!scope||!navigator.onLine)return;setBusy(true);setError('');try{await sync(scope);}catch(e){setError(e instanceof Error?e.message:'تعذرت المزامنة');}finally{setBusy(false);}},[scope]);
 useEffect(()=>{if(!scope||!online)return;void synchronize();const timer=setInterval(()=>void synchronize(),20000);return()=>clearInterval(timer);},[scope,online,synchronize]);
 async function login(org:DemoProfile){setBusy(true);setError('');try{if(pending.length&&org!==scope)throw new Error('زامن العمليات المعلقة أو صدّرها قبل تبديل المؤسسة.');let device=await local.preferences.get('device');if(!device){device={key:'device',value:crypto.randomUUID()};await local.preferences.put(device);}const response=await fetch('/api/v1/demo-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({organizationId:org,deviceId:device.value})});if(!response.ok)throw new Error('تعذر فتح الجلسة التجريبية');const downloaded=await bootstrap(org);await local.preferences.put({key:'scope',value:downloaded.organizationId});setScope(downloaded.organizationId);setSelected(null);setSearch('');setCategory('all');setStockFilter('all');await sync(org);}catch(e){setError(e instanceof Error?e.message:'تعذر الدخول');}finally{setBusy(false);}}
 async function resolveRow(row:LocalCommand,action:'retry'|'cancel'){try{await resolveReview(row.scope,row.id,action);if(action==='retry'&&online)await synchronize();}catch(e){setError(e instanceof Error?e.message:'تعذرت معالجة العملية');}}
 if(!ready)return <div className="loading"><div className="brand-mark" aria-hidden="true">f</div><p>تجهيز مساحة العمل…</p></div>;
 if(!snapshot)return <div className="welcome"><div className="welcome-card"><div className="brand-line"><div className="brand-mark" aria-hidden="true">f</div><strong dir="ltr">Fodo<span>إدارة المطاعم، ببساطة</span></strong></div><span className="eyebrow">إدارة المخزون والتكاليف</span><h1>مطعمك تحت السيطرة.<br/><em>أينما كنت.</em></h1><p>من المخزن إلى المطبخ، تابع الكميات والتكاليف في كل فرع. ويستمر يومك حتى لو انقطع الإنترنت.</p><div className="demo-note">نموذج تطوير محلي • بيانات تجريبية • ليس نظاماً إنتاجياً</div><button className="primary wide" disabled={busy||!online} onClick={()=>void login('grills')}>{busy?'تجهيز البيانات…':'فتح مجموعة المشاوي'}<Icon name="arrow"/></button><button className="secondary wide" disabled={busy||!online} onClick={()=>void login('bistro')}>تجربة مؤسسة منفصلة</button>{error&&<p role="alert" className="error">{error}</p>}{!online&&<p className="error">يلزم الاتصال لأول دخول وتنزيل البيانات.</p>}<div className="welcome-foot">مصر · العربية · فروع متعددة</div></div><div className="welcome-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="art-center"><span className="art-wordmark" dir="ltr">Fodo</span><span>كل التفاصيل. رؤية واحدة.</span></div><div className="float-card f1">المخزن المركزي <b>↗</b></div><div className="float-card f2">فروع متصلة <b>٣</b></div><div className="float-card f3">جاهز للعمل دون اتصال <b>✓</b></div></div></div>;
 const active=snapshot.locations.find(l=>l.id===location)!;
 const balance=(id:string)=>snapshot.balances.find(b=>b.locationId===location&&b.itemId===id);
 const total=snapshot.balances.filter(b=>b.locationId===location).reduce((v,b)=>v.add(b.value),decimal('0'));
 const low=snapshot.items.filter(i=>decimal(balance(i.id)?.quantity||'0').lt(i.minimum));
 const filtered=snapshot.items.filter(i=>`${i.name} ${i.sku} ${i.category}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())&&(category==='all'||i.category===category)&&(stockFilter==='all'||(stockFilter==='low'?decimal(balance(i.id)?.quantity||'0').lt(i.minimum):decimal(balance(i.id)?.quantity||'0').gte(i.minimum))));
 const entries=snapshot.entries.filter(e=>e.locationId===location);
 const currentCommands=pending.filter(p=>p.command.locationId===location).map(p=>p.command);
 const expired=Date.parse(snapshot.access.expiresAt)<=Date.now();
 const categories=[...new Set(snapshot.items.map(i=>i.category))].map(category=>({category,value:snapshot.items.filter(i=>i.category===category).reduce((v,i)=>v.add(balance(i.id)?.value||'0'),decimal('0'))}));
 const max=categories.reduce((v,c)=>c.value.gt(v)?c.value:v,decimal('1'));
 return <div className="shell">
  <aside className="sidebar"><div className="brand-line"><div className="brand-mark" aria-hidden="true">f</div><strong dir="ltr">Fodo<span dir="rtl">إدارة المطاعم، ببساطة</span></strong></div><div className="organization"><span className="tiny">المؤسسة الحالية</span><strong>{snapshot.organizationName}</strong><span className="tiny">مطاعم · مصر</span></div><span className="nav-caption">مساحة العمل</span><nav aria-label="التنقل الرئيسي">{(Object.keys(labels) as View[]).map(v=><button key={v} aria-current={view===v?'page':undefined} className={view===v?'nav-button active':'nav-button'} onClick={()=>setView(v)}><Icon name={v}/>{labels[v]}{v==='sync'&&pending.length>0&&<span className="count">{pending.length}</span>}</button>)}</nav><div className="sidebar-note"><Icon name="leaf"/><strong>كل فرع، في مكان واحد</strong><p>غيّر الموقع لتتابع الرصيد والتكلفة لكل مخزن أو مطبخ.</p></div><div className="sidebar-bottom"><span className="avatar">م</span><div><strong>مدير المؤسسة</strong><span>جلسة تجريبية محلية</span></div></div></aside>
  <div className="main"><header className="topbar"><div className="crumb">مساحة العمل <span>/</span> <strong>{labels[view]}</strong></div><div className="top-actions"><span className={`connection ${online?'':'offline'}`}><i/>{online?'متصل':'دون اتصال'}</span><button className="icon-button" aria-label="مزامنة الآن" disabled={busy||!online} onClick={()=>void synchronize()}><Icon name="sync"/></button><span className="avatar small" title="مدير المؤسسة">م</span></div></header>
   <main className="content"><div className="demo-banner">نسخة تطوير محلية <span>بيانات تجريبية • تكلفة المخزون تعتمد على FIFO • الضرائب ونظام POS غير مفعّلين</span></div>
    <div className="page-heading"><div><span className="eyebrow">المخزون والتكاليف</span><h1>{labels[view]}</h1><p>{view==='overview'?'أهلاً بك، هذه صورة مخزونك اليوم.':view==='inventory'?'ابحث عن المواد، وتابع الرصيد والتكلفة لكل موقع.':view==='activity'?'كل استلام وهالك، بتفاصيله ومرجعه.':'تابع ما تم إرساله وما يحتاج إلى انتباهك.'}</p></div><div className="heading-actions"><select aria-label="الموقع" value={location} onChange={e=>{setLocation(e.target.value);setSelected(null);}}>{snapshot.locations.map(l=><option value={l.id} key={l.id}>{l.name}</option>)}</select><button className="primary" onClick={e=>{operationTrigger.current=e.currentTarget;setEditing(undefined);setModal('receipt.post');}} disabled={expired}><Icon name="plus"/>استلام مواد</button><button className="secondary" onClick={e=>{operationTrigger.current=e.currentTarget;setEditing(undefined);setModal('waste.post');}} disabled={expired}>تسجيل هالك</button></div></div>
    {error&&<div role="alert" className="alert error">{error}<button onClick={()=>setError('')} aria-label="إغلاق التنبيه">×</button></div>}{notice&&<div role="status" className="alert success">{notice}<button onClick={()=>setNotice('')} aria-label="إغلاق التنبيه">×</button></div>}
    <div className="freshness"><span className="location-caption"><Icon name="inventory"/>{active.name} · {active.kind}</span><span>آخر تحديث: {date(snapshot.fetchedAt)} <b>·</b> {offlineReady?'التطبيق جاهز للفتح دون اتصال':'جارٍ تجهيز التطبيق للعمل دون اتصال'}</span></div>
    {expired&&<div className="alert error">انتهت صلاحية العمل دون اتصال. عملياتك المعلقة محفوظة.<button className="secondary" disabled={busy||!online} onClick={()=>void login(snapshot.organizationId)}>تجديد الجلسة الآن</button></div>}
    {(view==='overview'||view==='inventory')&&<><section className="metrics"><Metric label="قيمة المخزون المؤكدة" value={number(total.toString())} unit="ج.م" detail="القيمة النهائية بعد المزامنة" icon="inventory"/><Metric label="مواد في هذا الموقع" value={number(snapshot.items.length,0)} unit="مادة" detail="مواد مشتركة بين الفروع" icon="overview"/><Metric label="تحت الحد الأدنى" value={number(low.length,0)} unit="مادة" detail={low.length?'تحتاج إلى متابعة':'المستويات الحالية ضمن الحدود'} icon="activity"/><Metric label="عمليات تنتظر المزامنة" value={number(pending.length,0)} unit="عملية" detail={review.length?`${number(review.length)} عملية تحتاج مراجعة`:'محفوظة على هذا الجهاز'} icon="sync"/></section>
    {view==='overview'&&<section className="attention-panel" aria-label="متابعة اليوم"><div className="attention-heading"><span className="eyebrow">متابعة اليوم</span><h2>ما الذي يحتاج انتباهك؟</h2></div><button className="attention-action" onClick={()=>{setView('inventory');setStockFilter('low');setCategory('all');setSearch('');}}><span className="action-symbol warning"><Icon name="inventory"/></span><span><strong>{low.length?number(low.length,0)+' مواد تحت الحد الأدنى':'مستويات المخزون جيدة'}</strong><small>{low.length?'راجع المواد قبل الطلب التالي':'عرض المواد ومتابعة مستوياتها'}</small></span><Icon name="arrow"/></button><button className="attention-action" onClick={()=>setView('sync')}><span className="action-symbol"><Icon name="sync"/></span><span><strong>{review.length?number(review.length,0)+' عمليات تحتاج مراجعة':pending.length?number(pending.length,0)+' عمليات تنتظر الإرسال':'لا توجد عمليات معلقة'}</strong><small>افتح مركز المزامنة لتراجع التفاصيل</small></span><Icon name="arrow"/></button></section>}
    {view==='overview'&&<div className="insights"><section className="panel"><div className="panel-heading"><div><h2>توزيع قيمة المخزون</h2><p>حسب الفئة · رصيد مؤكد</p></div><span className="pill">ج.م</span></div><div className="bars">{categories.map(c=><div className="bar-row" key={c.category}><span>{c.category}</span><div className="track"><i style={{width:`${c.value.div(max).mul(100).toNumber()}%`}}/></div><strong>{number(c.value.toString())}</strong></div>)}</div></section><section className="panel calm"><span className="eyebrow">العمل دون اتصال</span><h2>الاتصال ينقطع.<br/>يومك يستمر.</h2><p>سجّل الاستلام والهالك دون اتصال. تجد العمليات محفوظة هنا حتى تتم المزامنة.</p><div className="sync-summary"><Icon name="check"/><span>{online?'يمكن المزامنة الآن':'سيتم الإرسال عند عودة الاتصال'}</span></div><button className="text-button" onClick={()=>setView('sync')}>عرض مركز المزامنة ←</button></section></div>}
    <section className="panel"><div className="panel-heading"><div><h2>مواد المخزون <span className="heading-count">{number(filtered.length,0)}</span></h2><p>اضغط على المادة لعرض طبقات تكلفتها</p></div><label className="search"><Icon name="search"/><input aria-label="بحث المواد" placeholder="ابحث باسم المادة أو الكود…" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button className="clear-search" aria-label="مسح البحث" onClick={()=>setSearch('')}><Icon name="close"/></button>}</label></div><div className="inventory-toolbar"><div className="filter-group"><label>الفئة<select aria-label="تصفية حسب الفئة" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">كل الفئات</option>{categories.map(c=><option key={c.category} value={c.category}>{c.category}</option>)}</select></label><label>حالة المخزون<select aria-label="تصفية حسب حالة المخزون" value={stockFilter} onChange={e=>setStockFilter(e.target.value)}><option value="all">كل المواد</option><option value="low">تحت الحد الأدنى</option><option value="available">رصيد كافٍ</option></select></label></div><span className="table-help">المؤكد: بعد المزامنة · المتوقع: يشمل العمليات المحلية</span></div><div className="table-scroll" tabIndex={0} aria-label="جدول مواد المخزون"><table><thead><tr><th>المادة</th><th>الفئة</th><th>الرصيد المؤكد</th><th>المتوقع محلياً</th><th>متوسط المتبقي</th><th>قيمة المخزون</th><th>الحالة</th></tr></thead><tbody>{filtered.map(i=>{const b=balance(i.id);const projected=projectedQuantity(snapshot,currentCommands,location,i.id);const isLow=decimal(b?.quantity||'0').lt(i.minimum);return <tr key={i.id}><td><button className="item-link" aria-expanded={selected===i.id} onClick={()=>setSelected(selected===i.id?null:i.id)}><span className={`item-icon cat-${i.id}`}><Icon name="inventory"/></span><span><strong>{i.name}</strong><small dir="ltr">{i.sku}</small></span></button></td><td>{i.category}</td><td><strong>{number(b?.quantity||'0',3)}</strong> <small>{i.unit}</small></td><td>{number(projected,3)} <small>{i.unit}</small>{projected!==decimal(b?.quantity||'0').toFixed(6)&&<small className="pending-label">غير نهائي</small>}</td><td>{b?.average?number(b.average):'—'} <small>ج.م</small></td><td>{number(b?.value||'0')} <small>ج.م</small></td><td><span className={`pill ${isLow?'warning':'good'}`}>{isLow?'منخفض':'متاح'}</span></td></tr>;})}</tbody></table>{!filtered.length&&<div className="empty"><Icon name="search"/><h3>لا توجد مواد مطابقة</h3><p>جرّب تغيير البحث أو الفلاتر.</p><button className="text-button" onClick={()=>{setSearch('');setCategory('all');setStockFilter('all');}}>عرض كل المواد</button></div>}</div>
     {selected&&<div className="layer-detail"><h3>طبقات التكلفة · {snapshot.items.find(i=>i.id===selected)?.name}</h3><p>الاستهلاك يبدأ بأقدم طبقة مقبولة.</p><div className="layer-list">{snapshot.layers.filter(l=>l.itemId===selected&&l.locationId===location).map((l,index)=><div key={l.id}><span>طبقة {number(index+1,0)}</span><strong>{number(l.remaining,3)} × {number(l.unitCost)} ج.م</strong></div>)}</div></div>}
    </section></>}
    {view==='activity'&&<section className="panel"><div className="panel-heading"><div><h2>حركات الموقع المقبولة</h2><p>سجل من الخادم، لا يتغير بمجرد تحديث الشاشة</p></div><span className="pill">آخر ١٠٠ حركة للمؤسسة</span></div><div className="table-scroll"><table><thead><tr><th>المادة</th><th>الحركة</th><th>الكمية</th><th>القيمة</th><th>المرجع / السبب</th><th>تاريخ العمل</th></tr></thead><tbody>{entries.map(e=><tr key={e.operationId}><td>{snapshot.items.find(i=>i.id===e.itemId)?.name}</td><td>{e.type==='opening'?'رصيد افتتاحي':e.type==='receipt.post'?'استلام':'هالك'}</td><td dir="ltr">{number(e.quantity,3)}</td><td>{number(e.amount)} ج.م</td><td>{e.reason}</td><td>{e.businessDate}</td></tr>)}</tbody></table></div></section>}
    {view==='sync'&&<><section className="panel sync-panel"><div><span className="eyebrow">حفظ محلي · قبول مركزي</span><h2>{review.length?`${number(review.length)} عملية تحتاج مراجعة`:pending.length?`${number(pending.length)} عملية محفوظة تنتظر المزامنة`:'كل العمليات مقبولة'}</h2><p>راجع حالة كل عملية أدناه. العمليات التي تحتاج مراجعة تبقى محفوظة ولا تغيّر الرصيد المؤكد.</p></div><div className="heading-actions"><button className="primary" disabled={busy||!online} onClick={()=>void synchronize()}><Icon name="sync"/>{busy?'جارٍ المزامنة…':'مزامنة الآن'}</button><button className="secondary" onClick={()=>void downloadRecovery(snapshot.organizationId)}>تصدير نسخة استرداد</button><button className="secondary" disabled={expired} onClick={()=>setRecoveryOpen(true)}>استعادة ملف</button></div></section><section className="panel"><div className="panel-heading"><h2>العمليات على هذا الجهاز</h2><span className="pill">{commands.length} عملية</span></div><div className="queue">{[...commands].reverse().map(c=><div className="queue-row" key={c.id}><span className="item-icon"><Icon name={c.status==='accepted'?'check':'sync'}/></span><div className="queue-info"><strong>{c.command.type==='receipt.post'?'استلام':'هالك'} · {snapshot.items.find(i=>i.id===c.command.itemId)?.name} · {number(c.command.quantity,3)}</strong><small>{snapshot.locations.find(l=>l.id===c.command.locationId)?.name} · {date(c.createdAt)}</small>{c.error&&<span className="error">{c.error}</span>}{c.resolution&&<small>{c.resolution}</small>}{c.replacesId&&<small>تصحيح لعملية سابقة · {c.replacesId.slice(0,8)}</small>}{c.status==='needsReview'&&<div className="review-actions"><button className="secondary" disabled={expired} onClick={()=>void resolveRow(c,'retry')}>إعادة المحاولة</button><button className="secondary" disabled={expired} onClick={e=>{operationTrigger.current=e.currentTarget;setEditing(c);setModal(c.command.type);}}>تصحيح العملية</button><button className="text-button" onClick={()=>void resolveRow(c,'cancel')}>إلغاء المرفوضة</button></div>}</div><span className={`pill ${c.status==='accepted'?'good':c.status==='needsReview'?'warning':''}`}>{c.status==='accepted'?'مقبولة':c.status==='needsReview'?'تحتاج مراجعة':c.status==='acceptedAwaiting'?'انتظار تنزيل النتيجة':c.status==='cancelled'?'ملغاة':c.status==='superseded'?'تم التصحيح':'محفوظة محلياً'}</span></div>)}{!commands.length&&<div className="empty"><Icon name="check"/><p>ستظهر عمليات الاستلام والهالك هنا.</p></div>}</div></section><section className="panel demo-controls"><div><h3>المؤسسات والجلسة</h3><p>بدّل البيانات التجريبية بعد مزامنة العمليات المعلقة.</p></div><button className="secondary" disabled={busy||!online||pending.length>0} onClick={()=>void login(scope==='grills'?'bistro':'grills')}>فتح {scope==='grills'?'بيت المذاق':'مجموعة المشاوي'}</button><button className="secondary" disabled={busy||!online} onClick={()=>void login(snapshot.organizationId)}>تجديد الجلسة</button></section></>}
    <footer className="page-footer"><span>Fodo · إدارة المطاعم</span><BuildVersion/><span>الفواتير الضريبية والوصفات والتحويلات قيد التطوير</span></footer>
   </main>
  </div>
  {recoveryOpen&&<RecoveryDialog scope={snapshot.organizationId} close={()=>setRecoveryOpen(false)} saved={()=>{setRecoveryOpen(false);setNotice('تمت استعادة العمليات. راجع حالتها في القائمة.');if(online)void synchronize();}}/>}
  {modal&&<OperationModal type={modal} initial={editing} snapshot={snapshot} location={editing?.command.locationId||location} close={()=>setModal(null)} saved={()=>{setModal(null);setNotice('تم الحفظ على هذا الجهاز. ستظهر النتيجة النهائية بعد المزامنة.');if(online)void synchronize();}}/>}
 </div>;
}
function Metric({label,value,unit,detail,icon}:{label:string;value:string;unit:string;detail:string;icon:string}){return <article className="metric"><div className="metric-top"><span>{label}</span><span className="metric-icon"><Icon name={icon}/></span></div><div className="metric-value">{value}<small>{unit}</small></div><p>{detail}</p></article>;}
type FormValues={itemId:string;quantity:string;unitCost:string;reason:string};
function OperationModal({type,initial,snapshot,location,close,saved}:{type:Command['type'];initial?:LocalCommand;snapshot:Snapshot;location:string;close:()=>void;saved:()=>void}){
 const {register,handleSubmit,watch,formState:{errors,isSubmitting}}=useForm<FormValues>({defaultValues:{itemId:initial?.command.itemId||snapshot.items[0].id,quantity:initial?.command.quantity||'',unitCost:initial?.command.unitCost||'',reason:initial?.command.reason||''}});const [error,setError]=useState('');const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{dialog.current?.showModal();},[]);const item=snapshot.items.find(i=>i.id===watch('itemId'))!;const receipt=type==='receipt.post';const quantity=watch('quantity');const unitCost=watch('unitCost');const available=snapshot.balances.find(b=>b.locationId===location&&b.itemId===item.id)?.quantity||'0';const validNumber=(v:string)=>/^(?:0|[1-9]\d{0,8})(?:\.\d{1,6})?$/.test(v||'');const estimated=receipt&&validNumber(quantity)&&validNumber(unitCost)?decimal(quantity).mul(unitCost).toFixed(2):null;
 async function submit(values:FormValues){try{setError('');const businessDate=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const c=commandSchema.parse({operationId:crypto.randomUUID(),organizationId:snapshot.organizationId,locationId:location,type,itemId:values.itemId,quantity:values.quantity,unitCost:receipt?values.unitCost:undefined,reason:values.reason,businessDate,capturedAt:new Date().toISOString(),schemaVersion:1});if(initial)await resolveReview(snapshot.organizationId,initial.id,'correct',c);else await saveCommand(c);saved();}catch(e){setError(e instanceof Error&&e.name!=='ZodError'?e.message:'تحقق من الكمية والتكلفة. استخدم أرقاماً مثل 1.25.');}}
 return <dialog ref={dialog} aria-labelledby="dialog-title" className="modal" onCancel={e=>{e.preventDefault();if(!isSubmitting)close();}}><div className="modal-intro"><span className="action-symbol"><Icon name={receipt?'plus':'activity'}/></span><span>{receipt?'إضافة مواد إلى مخزون الموقع':'توثيق المواد التالفة أو المهدرة'}</span></div><div className="panel-heading"><div><span className="eyebrow">{snapshot.locations.find(l=>l.id===location)?.name}</span><h2 id="dialog-title">{receipt?'استلام مواد':'تسجيل هالك'}</h2></div><button className="icon-button" disabled={isSubmitting} onClick={close} aria-label="إغلاق"><Icon name="close"/></button></div><form onSubmit={handleSubmit(submit)}><label>المادة<select aria-label="المادة" {...register('itemId')}>{snapshot.items.map(i=><option key={i.id} value={i.id}>{i.name} · {i.unit}</option>)}</select></label><div className="form-row"><label>الكمية ({item.unit})<input autoFocus aria-label={`الكمية (${item.unit})`} aria-invalid={!!errors.quantity} inputMode="decimal" dir="ltr" placeholder="0.00" {...register('quantity',{setValueAs:normalizeDecimal,required:'الكمية مطلوبة',validate:v=>/^(?:0|[1-9]\d{0,8})(?:\.\d{1,6})?$/.test(v)&&Number(v)>0||'أدخل كمية موجبة'})}/>{errors.quantity&&<small className="error">{errors.quantity.message}</small>}</label>{receipt&&<label>تكلفة الوحدة (ج.م)<input aria-label="تكلفة الوحدة (ج.م)" aria-invalid={!!errors.unitCost} inputMode="decimal" dir="ltr" placeholder="0.00" {...register('unitCost',{setValueAs:normalizeDecimal,required:'التكلفة مطلوبة',validate:v=>validNumber(v)||'أدخل تكلفة صحيحة'})}/>{errors.unitCost&&<small className="error">{errors.unitCost.message}</small>}</label>}</div><label>{receipt?'مرجع الاستلام':'سبب الهالك'}<input aria-label={receipt?'مرجع الاستلام':'سبب الهالك'} aria-invalid={!!errors.reason} placeholder={receipt?'رقم فاتورة المورد أو ملاحظة':'تلف، انسكاب، انتهاء صلاحية…'} {...register('reason',{required:'المرجع أو السبب مطلوب',minLength:{value:2,message:'أدخل حرفين على الأقل'},maxLength:200})}/>{errors.reason&&<small className="error">{errors.reason.message}</small>}</label><div className="operation-summary"><span>{receipt?'إجمالي الاستلام المتوقع':'الرصيد المؤكد المتاح'}</span><strong>{receipt?(estimated?number(estimated)+' ج.م':'—'):number(available,3)+' '+item.unit}</strong></div>{!receipt&&validNumber(quantity)&&decimal(quantity).gt(available)&&<p className="form-warning">الكمية أكبر من الرصيد المؤكد. يمكنك حفظها محلياً، وستحتاج مراجعة إذا لم يتوفر الرصيد عند المزامنة.</p>}<div className="form-note"><Icon name="sync"/><span>تُحفظ على هذا الجهاز أولاً. تصبح نهائية بعد قبول المزامنة.</span></div>{error&&<p role="alert" className="error">{error}</p>}<div className="modal-actions"><button className="primary" type="submit" disabled={isSubmitting}>{isSubmitting?'جارٍ الحفظ…':'حفظ العملية'}</button><button className="secondary" type="button" disabled={isSubmitting} onClick={close}>إلغاء</button></div></form></dialog>;
}
